spring:
  main:
    allow-circular-references: true
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml
  batch:
    job:
      enabled: true
  shell:
    interactive:
      enabled: true

  mongodb:
    embedded:
      version: 3.4.0

  data:
    mongodb:
      host: localhost
      port: 7071
      database: lib

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console
