spring:
  data:
    mongodb:
      uri: mongodb://localhost:7071
      database: library

mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.homework.mongock.changelog